### ISSUE TITLE
Startup error 

### ISSUE THREAD

**Issue by ttk2** [Celdecea/MusterCull#1]
2012-07-21 04:09:24 [INFO] Loading MusterCull Configuration...
2012-07-21 04:09:24 [INFO] Culling CREEPER using SPAWN with a limit of 10 and a range of 100
2012-07-21 04:09:24 [INFO] Culling SKELETON using SPAWN with a limit of 10 and a range of 100
2012-07-21 04:09:24 [INFO] Culling SPIDER using SPAWN with a limit of 10 and a range of 100
2012-07-21 04:09:24 [INFO] Culling ZOMBIE using SPAWN with a limit of 10 and a range of 100
2012-07-21 04:09:24 [INFO] Culling GHAST using SPAWN with a limit of 1 and a range of 100
2012-07-21 04:09:24 [SEVERE] Error occurred while enabling MusterCull v0.1 (Is it up to date?)
java.lang.NullPointerException
        at com.untamedears.mustercull.Configuration.setLimit(Configuration.java:173)
        at com.untamedears.mustercull.Configuration.load(Configuration.java:99)
        at com.untamedears.mustercull.MusterCull.onEnable(MusterCull.java:44)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)

**Comment by Celdecea** [comment]
You are getting this error because I used the wrong names in the config file. For example, CAVE_SPIDER should be CAVESPIDER and MAGMA_CUBE is LAVASLIME.  

The new .jar is available on the test server which reports this error better. The uploaded configuration file has been corrected too but the values are test values from my own server.

Thanks for the issue report.
